<a href="https://colab.research.google.com/github/Jakelinecs/Tareas-Machine-Learning/blob/main/N7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result_numpy = np.matmul(a_ndarray, b_ndarray)

print("--- 行列積を理解しよう (NumPy) ---")
print("行列 A:\n", a_ndarray)
print("\行列 B:\n", b_ndarray)
print("\nResultado (A @ B):\n", result_numpy)

--- 行列積を理解しよう (NumPy) ---
行列 A:
 [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
\行列 B:
 [[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]

Resultado (A @ B):
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
def matmul_scratch(a, b):
    result = np.zeros((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]

    return result

scratch_result = matmul_scratch(a_ndarray, b_ndarray)

print("--- Producto de Matrices (Scratch) ---")
print("Resultado (A @ B) - Scratch:\n", scratch_result)

is_equal = np.array_equal(result_numpy, scratch_result)
print(f"\n¿El resultado scratch coincide con el resultado NumPy?: {is_equal}")

--- Producto de Matrices (Scratch) ---
Resultado (A @ B) - Scratch:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]

¿El resultado scratch coincide con el resultado NumPy?: True


In [7]:
#####################################################################################################################

In [8]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]]) # Forma (2, 3)
e_ndarray = np.array([[-9, 8, 7, 6], [-5, 4, 3, 2]]) # Forma (2, 4)

def is_multiplicable(a, b):
    if a.shape[1] != b.shape[0]:
        print(f"行列積を計算できません。列数と行数が一致しません。")
        return False
    return True

print("\n--- Verificación de la Multiplicabilidad ---")

# Verificar si D @ E es posible: (2, 3) @ (2, 4) -> No
print("Verificando D @ E:")
if is_multiplicable(d_ndarray, e_ndarray):
    print("Resultado (D @ E):\n", np.matmul(d_ndarray, e_ndarray))


--- Verificación de la Multiplicabilidad ---
Verificando D @ E:
行列積を計算できません。列数と行数が一致しません。


In [4]:
print("\n--- Producto con Transposición (D.T @ E) ---")

d_transposed = d_ndarray.T # Forma (3, 2)
# e_ndarray tiene forma (2, 4)

# Verificar si D.T @ E es posible: (3, 2) @ (2, 4) -> Sí
print("Verificando D.T @ E:")
if is_multiplicable(d_transposed, e_ndarray):
    result_transposed = np.matmul(d_transposed, e_ndarray)
    print("\nResultado (D.T @ E) - Posible:\n", result_transposed)
else:
     print("Error: La operación con D.T tampoco es posible con estas formas.")


--- Producto con Transposición (D.T @ E) ---
Verificando D.T @ E:

Resultado (D.T @ E) - Posible:
 [[-11   8   5   2]
 [  7  -4  -1   2]
 [-57  48  39  30]]
